### ISSUE TITLE
feat : Bottom Navigation 구현

### ISSUE THREAD

**Issue by ss99x2002** [ss99x2002/OurCourage-Android-v2#15]
## Issue 🛠
Compose 로 Bottom Navigation을 구현합니다.

## To-do
- [x] Bottom Navigation ui 구현
- [x] HomeScreen, ScanActivity, MyPageScreen, PointHistoryScreen 연결
- [x] Navigation 화면 간 이동 구현
추가로 진행 할 예정인 부분 ++
- [ ] amulator 실행 후 디바이스 modifier 화면 대응 에러 수정
- [ ] Compose Navigation 동작 원리 공부
- [ ] Navigation 이동과 Compose 서버통신 데이터 가져오기 공부 
- [x] Navigation 함수,변수명 일관성 맞추기 (Point ->PointHistory / Camera -> Scan 등..)
- [ ] 간결한 Navigation 적용 방법 알아보기 

## Study
- **[Compose Navigation으로 화면간 이동](https://m.blog.naver.com/comye1/222457844226)**
- **[Compose Navigation 안드로이드 공식문서](https://developer.android.com/develop/ui/compose/navigation?hl=ko#kts)**
- **[Compose Navigation Bottom Navigation 예제](https://onlyfor-me-blog.tistory.com/764)**
- 논의 해볼만한 내용 : Navigation에서 Sealed class vs enum class ?
