### ISSUE TITLE
feat : QR Scanner Activity와 Navigation 연결 

### ISSUE THREAD

**Issue by ss99x2002** [ss99x2002/OurCourage-Android-v2#40]
## Issue 🛠
QR Scanner AndroidView와 Compose Navigation을 연결합니다.
## To-do
- [x] QR Scanner Zxing AndroidView로 구현 
- [x] 백스택에 있을 때 Scanner 작동하지 않도록 구현 -> 프로세서 부하, UI 성능 저하 막기 위함
- [x] 반납 로직 Navigation 흐름 완성
- [x] 대여 로직 Navigation 흐름 완성 
## Study 

- Navigation 처리 및 화면 이동 간 데이터 관리 공부 필요
